package sample.data.jpa.domain;
// Imports ...

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "users")
public class User {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  @NotNull
  @Column(name = "email")
  private String email;
  
  @NotNull
  @Column(name = "name")
  private String name;

    public User(String email, String name) {
    }

    public User(long id) {
    }
}